Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: dynamodbAccessRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource: "*"
  InitFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: >
          const AWS = require("aws-sdk");
          const response = require('./cfn-response');
          const docClient = new AWS.DynamoDB.DocumentClient();
          exports.handler = function(event, context) {
            console.log(JSON.stringify(event,null,2));
            var params = {
              RequestItems: {
                "Caching-ReadingLogs": [
                  {
                    PutRequest: {
                      Item: {
                        userId: "8f4d9aa0-7180-4f23-8a59-8cc5a0786b44",
                        isbn: "9780739303405",
                        date: "2020-04-26T21:55:38Z",
                        status: "CURRENTLY_READING",
                        page: 26
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        userId: "8f4d9aa0-7180-4f23-8a59-8cc5a0786b44",
                        isbn: "9780739303405",
                        date: "2020-04-25T21:55:38Z",
                        status: "CURRENTLY_READING",
                        page: 0
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        userId: "8f4d9aa0-7180-4f23-8a59-8cc5a0786b44",
                        isbn: "9780385480017",
                        date: "2020-04-17T23:30:38Z",
                        status: "READ",
                        page: 100
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        userId: "8f4d9aa0-7180-4f23-8a59-8cc5a0786b44",
                        isbn: "9783644406759",
                        date: "2020-04-02T11:23:38Z",
                        status: "READ",
                        page: 100
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        userId: "8f4d9aa0-7180-4f23-8a59-8cc5a0786b44",
                        isbn: "9780525655244",
                        date: "2020-04-01T11:34:38Z",
                        status: "CURRENTLY_READING",
                        page: 0
                      }
                    }
                  }
                ]
              }
            };
            docClient.batchWrite(params, function(err, data) {
              if (err) {
                response.send(event, context, "FAILED", {});
              } else {
                response.send(event, context, "SUCCESS", {});
              }
            });
          };
      Handler: index.handler
      Role:
        Fn::GetAtt: [ LambdaRole , "Arn" ]
      Runtime: nodejs12.x
      Timeout: 60
  CachingClassroomReadingLogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions" : [
        {
          "AttributeName" : "userId",
          "AttributeType" : "S"
        },
        {
          "AttributeName": "isbn",
          "AttributeType": "S"
        },
        {
          "AttributeName": "date",
          "AttributeType": "S"
        },
        {
          "AttributeName": "status",
          "AttributeType": "S"
        }
      ]
      "KeySchema" : [
        {
          "AttributeName" : "userId",
          "KeyType" : "HASH"
        },
        {
          "AttributeName": "date",
          "KeyType": "RANGE"
        }
      ]
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      BillingMode: PAY_PER_REQUEST
      TableName: "Caching-ReadingLogs"
      GlobalSecondaryIndexes:
        - IndexName: "userId-isbn"
          KeySchema:
            - AttributeName: "userId"
              KeyType: "HASH"
            - AttributeName: "isbn"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
        - IndexName: "userId-status"
          KeySchema:
            - AttributeName: "userId"
              KeyType: "HASH"
            - AttributeName: "status"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
  InitializeEventsTable:
    Type: Custom::InitFunction
    DependsOn: CachingClassroomReadingLogTable
    Properties:
      ServiceToken:
        Fn::GetAtt: [ InitFunction , "Arn" ]
      DynamoTableName:
        Ref: CachingClassroomReadingLogTable